name: CI
on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  ci:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Get pip cache dir
        id: pip-cache
        run: |
          python -m pip install --upgrade pip wheel
          echo "::set-output name=dir::$(pip cache dir)"

      - name: pip cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}

      - name: Test with pytest
        run: |
          pip install .
          pytest tests/
      
